# -*- coding: utf-8 -*-
"""Cópia de 3_Exercícios_de_Function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14BSCPEpftAlKgKLK_mScS91FUQnACoYe

# Exercícios

### Antes de irmos para o desafio que apresentamos na última aula (que é bem mais complexo do que um exemplo simples) vamos resolver um exercício um pouco mais simples para treinar

## 1. Cálculo do Percentual e da Lista de Vendedores

- Queremos criar uma function que consiga identificar os vendedores que bateram uma meta, mas além disso, consigo já me dar como resposta o cálculo do % da lista de vendedores que bateu a meta (para eu não precisar calcular manualmente depois)
- Essa function deve receber 2 informações como parâmetro: a meta e um dicionário com os vendedores e suas vendas. E me dar 2 respostas: uma lista com o nome dos vendedores que bateram a meta e o % de vendedores que bateu a meta.
"""

meta = 10000
vendas = {
    'João': 15000,
    'Julia': 27000,
    'Marcus': 9900,
    'Maria': 3750,
    'Ana': 10300,
    'Alon': 7870,
}

#crie sua function aqui
def calcular_vendedores_que_bateram_meta(meta, vendas):
  vendedores_que_bateram_meta = []
  total_de_vendedores = len(vendas)

  for nome_vendedor, valor_venda in vendas.items():
    if valor_venda >= meta:
      vendedores_que_bateram_meta.append(nome_vendedor)

  percentual_vendedores_que_bateram_meta = (len(vendedores_que_bateram_meta) / total_de_vendedores) * 100

  return vendedores_que_bateram_meta, percentual_vendedores_que_bateram_meta

#aplique sua function nas informações para ver se está funcionando
vendedores_que_bateram_meta, percentual = calcular_vendedores_que_bateram_meta(meta, vendas)

print(f"Vendedores que bateram a meta: {vendedores_que_bateram_meta}")
print(f"Percentual de vendedores que bateram a meta: {percentual:.2f}%")

